// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpEz07X6HI_0cnT2LWEwKjKkEP_R0nQ0',
    appId: '1:931751211498:web:18fde140f18a9d26b14293',
    messagingSenderId: '931751211498',
    projectId: 'stafftrack-85d76',
    authDomain: 'stafftrack-85d76.firebaseapp.com',
    storageBucket: 'stafftrack-85d76.firebasestorage.app',
    measurementId: 'G-WVWWG769EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATa3HZD_Vl0qYlzBq-GRFCjf2y72lodMU',
    appId: '1:931751211498:android:8208725878b8e4f7b14293',
    messagingSenderId: '931751211498',
    projectId: 'stafftrack-85d76',
    storageBucket: 'stafftrack-85d76.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCpEz07X6HI_0cnT2LWEwKjKkEP_R0nQ0',
    appId: '1:931751211498:web:f6da2d23ed169c87b14293',
    messagingSenderId: '931751211498',
    projectId: 'stafftrack-85d76',
    authDomain: 'stafftrack-85d76.firebaseapp.com',
    storageBucket: 'stafftrack-85d76.firebasestorage.app',
    measurementId: 'G-ZPKL4NBDQ8',
  );
}
